### ISSUE TITLE
Every time I open movies hub I get UnicodeEncodeError

### ISSUE THREAD

**Issue by markcahigyan** [sualfred/script.embuary.helper#27]
Hi,
I'm using now the latest version of emby skin on Kodi 18.4, every time I open up the movies hub this error is generated:

> ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.embuary.helper/plugin.py", line 76, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/script.embuary.helper/plugin.py", line 31, in __init__
                                                self.listing()
                                              File "/storage/.kodi/addons/script.embuary.helper/plugin.py", line 54, in listing
                                                PluginListing(self.params,li)
                                              File "/storage/.kodi/addons/script.embuary.helper/resources/lib/plugin_listing.py", line 91, in __init__
                                                self.list_widgets()
                                              File "/storage/.kodi/addons/script.embuary.helper/resources/lib/plugin_listing.py", line 160, in list_widgets
                                                category_label=category_label
                                              File "/storage/.kodi/addons/script.embuary.helper/resources/lib/plugin_listing.py", line 196, in _encode_url
                                                return '{0}?{1}'.format(sys.argv[0], urlencode(kwargs))
                                              File "/usr/lib/python2.7/urllib.py", line 1342, in urlencode
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
                                            -->End of Python script error report<--

Thanks in advance.

**Comment by sualfred** [comment]
@markcahigyan 

Can you please upload me your MyVideos116.db so I'm able to reproduce it on my end? It's just a few MB and stored in your userdata/database folder of Kodi.

https://wetransfer.com/ or google drive or onedrive, dropbox, etc. Any cloud hoster is fine

**Comment by sualfred** [comment]
@markcahigyan 
I have a feeling what is causing it and pushed a new version to my repo. Please let me know if that fixed it.

**Comment by markcahigyan** [comment]
Works like a charm. Thank you 👍
