### ISSUE TITLE
Cinema Mode not working

### ISSUE THREAD

**Issue by donkristo** [sualfred/script.embuary.helper#29]
Hi Sebastian,

when I try to use Cinema Mode I get an error when I start playing a movie in cinema mode. The following log may help to debug. I use Embuary Skin with Kodi v18.5 without Emby, only local movies and TV shows.

thx

> 2019-12-04 06:33:28.257 T:5072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'movie_properties' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\default.py", line 43, in <module>
                                                Main()
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\default.py", line 19, in __init__
                                                self.getactions()
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\default.py", line 39, in getactions
                                                util(self.params)
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\resources\lib\utils.py", line 36, in playcinema
                                                dbtype=params.get('type')
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\resources\lib\cinema_mode.py", line 34, in __init__
                                                self.run()
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\resources\lib\cinema_mode.py", line 43, in run
                                                movies = self.get_trailers()
                                              File "C:\Users\me\AppData\Roaming\Kodi\addons\script.embuary.helper\resources\lib\cinema_mode.py", line 100, in get_trailers
                                                properties=movie_properties,
                                            NameError: global name 'movie_properties' is not defined
                                            -->End of Python script error report<--

**Comment by sualfred** [comment]
Thanks, fixed in the next version.

If you can't wait simply add this small line locally: https://github.com/sualfred/script.embuary.helper/commit/2592b74f6a667ad59c26f9acf630ad756b70d1c2

**Comment by donkristo** [comment]
Now it works. Thank you very much for this quick fix!
