### ISSUE TITLE
Embuary Helper Script Error constantly

### ISSUE THREAD

**Issue by luthepa1** [sualfred/script.embuary.helper#40]
Hi,  I started receiving errors recently with the helper script and I am not sure why.  I run Fedora 31 and the errors seem to have happened after system updates recently and now occurring on a 2nd PC after updates.  Suspecting its due to numpy updating to a more recent version or something along those lines.

-Kodi 18.6 
-Embuary Skin 18.8.9
-Embuary Helper Script 1.4.5

`2020-04-16 18:59:42.682 T:140112419346176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/htpc/.kodi/addons/script.embuary.helper/plugin.py", line 16, in <module>
                                                from resources.lib.plugin_content import *
                                              File "/home/htpc/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
                                                from resources.lib.image import *
                                              File "/home/htpc/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                from PIL import ImageFilter,Image,ImageOps
                                              File "/usr/lib64/python2.7/site-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib64/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib64/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib64/python2.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib64/python2.7/site-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--`

[kodi.log](https://github.com/sualfred/script.embuary.helper/files/4486195/kodi.log)

any ideas how to resolve?

Regards,

Paul.

**Comment by sualfred** [comment]
Not related to the script. 
It's an open issue of the installed Numpy package on your system. Try to reinstall Numpy/Pillow/PIL. Google is your friend in this case, it's a known issue.

**Comment by luthepa1** [comment]
My apologies. I didn't understand the github interface to realised there are already "closed issues" and this error already reported.  Sorry about that.  I had figured out numpy was an issue but not realise possibly pillow and pil as well.  Thank you for still taking the time to respond to me.

**Comment by sualfred** [comment]
Np
