### ISSUE TITLE
Embuary Helper 2.0.6 crashing on Raspberry Pi OS 2020-08-20 with Kodi 18.9.702

### ISSUE THREAD

**Issue by eggplant37** [sualfred/script.embuary.helper#45]
Call to /usr/lib/python3/dist-packages/numpy/core/overrides.py line 46 results in following exception thrown when running Embuary Helper on Kodi 18.9.702 on Raspberry Pi OS 2020-08-20 with python 3.7:

`2020-10-26 23:03:52.665 T:18302   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: implement_array_function method already has a docstring
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/script.embuary.helper/default.py", line 8, in <module>
                                                       from resources.lib.utils import *
                                                     File "/home/pi/.kodi/addons/script.embuary.helper/resources/lib/utils.py", line 20, in <module>
                                                       from resources.lib.image import *
                                                     File "/home/pi/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                       from PIL import ImageFilter,Image,ImageOps
                                                     File "/usr/lib/python3/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                       import numpy
                                                     File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
                                                       from . import core
                                                     File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                       from . import multiarray
                                                     File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 12, in <module>
                                                       from . import overrides
                                                     File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                       """)
                                                   RuntimeError: implement_array_function method already has a docstring
                                                   -->End of Python script error report<--
                                                   
2020-10-26 23:03:52.666 T:18302   DEBUG <general>: onExecutionDone(14, /home/pi/.kodi/addons/script.embuary.helper/default.py)`

Clues to resolve would be helpful. I'm compiling from source via git.

**Comment by sualfred** [comment]
It's the distro provided numpy package which is crashing. Not related to this script or Kodi.

**Comment by eggplant37** [comment]
So to solve the problem, I've apt purged python3-numpy and its associated packages from my Raspberry PI OS install, and then used pip3 install numpy to reinstall it. Voila, problem solved. Hope this helps others find a solution.

**Comment by sualfred** [comment]
Thanks.

**Comment by testbughub** [comment]
> So to solve the problem, I've apt purged python3-numpy and its associated packages from my Raspberry PI OS install, and then used pip3 install numpy to reinstall it. Voila, problem solved. Hope this helps others find a solution.

I tried this as well, but it still get this error.
I've googled a bunch, and tried every single thing mentioned, but nothing seem to work.
There are some different theories on why this happens, but some clarification would be appreciated.
Is it pillow or numpy that's the culprit?
