### ISSUE TITLE
ImportError: PIL/_imaging.so: undefined symbol: XauGetBestAuthByAddr

### ISSUE THREAD

**Issue by nzhang9999** [sualfred/script.embuary.helper#64]
I'm using CoreELEC 19.3 for Phicomm N1, package from https://github.com/RuralHunter/CoreELEC

I got error info fom Embuary Helper after i install Embuary Skin

### Log info
```python
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ImportError'>
Error Contents: /usr/lib/python3.8/site-packages/PIL/_imaging.so: undefined symbol: XauGetBestAuthByAddr
Traceback (most recent call last):
  File "/storage/.kodi/addons/script.embuary.helper/plugin.py", line 10, in <module>
    from resources.lib.plugin_content import *
  File "/storage/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
    from resources.lib.image import *
  File "/storage/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
    from PIL import ImageFilter,Image,ImageOps,ImageEnhance
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
     ImportError: /usr/lib/python3.8/site-packages/PIL/_imaging.so: undefined symbol: XauGetBestAuthByAddr
  -->End of Python script error report<--
```

### Additional context

```python
CoreELEC (RuralHunter): 19.3 (Amlogic-ng.arm)
CoreELEC:~ # python
Python 3.8.11 (default, Oct  9 2021, 12:19:08)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
ImportError: /usr/lib/python3.8/site-packages/PIL/_imaging.so: undefined symbol: XauGetBestAuthByAddr
```

**Comment by biaji** [comment]
Same here. It look llike PIL depend on libXau.so. And my box missing that.

Coreelec 19.3

@nzhang9999 do you have a fix of this now?
