### ISSUE TITLE
Continue Watching widget is broken. (PIL error?)

### ISSUE THREAD

**Issue by jiminorris** [sualfred/script.embuary.helper#68]
A recent update of my python libraries has broken the script. I'm sure it is linked to calls to the PIL based on the log information. 

```
2023-03-31 09:56:27.160 T:4296    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : 
							-->Python callback/script returned the following error<--
			- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
			Error Type: <class 'ImportError'>
			Error Contents: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
			Traceback (most recent call last):
			File "/.kodi/addons/script.embuary.helper/service.py", line 6, in <module> from resources.lib.service_monitor import *
			File "/.kodi/addons/script.embuary.helper/resources/lib/service_monitor.py", line 12, in <module> from resources.lib.utils import split
			File "/.kodi/addons/script.embuary.helper/resources/lib/utils.py", line 20, in <module> from resources.lib.image import *
			File "/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module> from PIL import ImageFilter,Image,ImageOps,ImageEnhance
			File "/usr/lib/python3/dist-packages/PIL/Image.py", line 103, in <module> from . import _imaging as core
			ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
								-->End of Python script error report<--

```

**Comment by jiminorris** [comment]
This was Matrix only, Nexus worked fine.
