### ISSUE TITLE
[MATRIX] No module named 'PIL'

### ISSUE THREAD

**Issue by Benna80** [sualfred/script.embuary.helper#69]
i'm running KODI 19.5 on QNAP NAS and i keep getting error from Embuary Helper.
This is what log file says:

 EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'PIL'
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi19L/.kodi/addons/script.embuary.helper/plugin.py", line 10, in <module>
                                                       from resources.lib.plugin_content import *
                                                     File "/opt/Kodi19L/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
                                                       from resources.lib.image import *
                                                     File "/opt/Kodi19L/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
                                                       from PIL import ImageFilter,Image,ImageOps,ImageEnhance
                                                   ModuleNotFoundError: No module named 'PIL'
                                                   -->End of Python script error report<--
                                                   
2023-07-06 08:31:52.253 T:6232     INFO <general>: Python interpreter stopped

Installing Kodi 19.5 on windows this doesn't happen.
Is this behaviour known?

**Comment by Benna80** [comment]
Fixed, is not a problem related to this add-on but needed to install python-pil package via apt-get.
